### ISSUE TITLE
About liblietorch.so

### ISSUE THREAD

**Issue by ywaison** [youmi-zym/GO-SLAM#14]
Hi,
Thanks a lot for sharing this great project!
When I ran the command "./evaluate_on_replica.sh rgbd first_try" I encountered a problem
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    from src.slam import SLAM
  File "/home/gtyssg/GO-SLAM/src/slam.py", line 8, in <module>
    from lietorch import SE3
  File "/home/gtyssg/miniconda3/envs/go-slam/lib/python3.7/site-packages/lietorch/__init__.py", line 73, in <module>
    _init_backend()
  File "/home/gtyssg/miniconda3/envs/go-slam/lib/python3.7/site-packages/lietorch/__init__.py", line 51, in _init_backend
    raise FileNotFoundError(f"Error: Could not find {libpath}")
FileNotFoundError: Error: Could not find /home/gtyssg/miniconda3/envs/go-slam/lib/python3.7/site-packages/lietorch/lib/liblietorch.so
Has anyone else had this issue before? Any help would be greatly appreciated!

**Comment by ywaison** [comment]
my cuda version is11.7,python version is 3.9.7

**Comment by glaciomarine** [comment]
Can I ask you how to install tiny-cuda-nn

**Comment by ywaison** [comment]
> Can I ask you how to install tiny-cuda-nn

I downloaded tiny-cuda-nn as per the readme

**Comment by ywaison** [comment]
> Hi,
> 
> I have to say sorry that I didn't meet these issues when I prepared my environment. As for issues related to the installation, such as tiny-cuda-nn or lietorch, I think it'd be better to resort to the original repo. Anyway, if anyone who knows how to solve it, please help!!!
> 
> Best, Youmin

Thank you so much for the code, I had the same issue when I configured realtime-recon

**Comment by Renjave** [comment]
i met it;make sure your cuda version ;then remove conda env and conda create requirement

**Comment by gaojianzhen** [comment]
hi，i know how to install  liblietorch,
1. git clone https://github.com/princeton-vl/DROID-SLAM.git,
2.pip install thirdparty/lietorch. 
3.change dir in <setup.py>  include_dirs=[osp.join(ROOT, '/home/........your eigen3 dir ')],
you can try

**Comment by gaojianzhen** [comment]
> Can I ask you how to install tiny-cuda-nn
 
https://github.com/HengyiWang/Co-SLAM/tree/main.
.hi,  you can use it to   install tiny-cuda-nn

**Comment by gaojianzhen** [comment]
> Hi, Thanks a lot for sharing this great project! When I ran the command "./evaluate_on_replica.sh rgbd first_try" I encountered a problem Traceback (most recent call last): File "run.py", line 8, in from src.slam import SLAM File "/home/gtyssg/GO-SLAM/src/slam.py", line 8, in from lietorch import SE3 File "/home/gtyssg/miniconda3/envs/go-slam/lib/python3.7/site-packages/lietorch/**init**.py", line 73, in _init_backend() File "/home/gtyssg/miniconda3/envs/go-slam/lib/python3.7/site-packages/lietorch/**init**.py", line 51, in _init_backend raise FileNotFoundError(f"Error: Could not find {libpath}") FileNotFoundError: Error: Could not find /home/gtyssg/miniconda3/envs/go-slam/lib/python3.7/site-packages/lietorch/lib/liblietorch.so Has anyone else had this issue before? Any help would be greatly appreciated!

hi，i know how to install liblietorch,

git clone https://github.com/princeton-vl/DROID-SLAM.git,
2.pip install thirdparty/lietorch.
3.change dir in <setup.py> include_dirs=[osp.join(ROOT, '/home/........your eigen3 dir ')],
you can try
