### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by small-zeng** [youmi-zym/GO-SLAM#3]
Thanks for your nice work, when I run `python setup.py install`, It occur:

`python3 setup.py install
running install
/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing droid_backends.egg-info/PKG-INFO
writing dependency_links to droid_backends.egg-info/dependency_links.txt
writing top-level names to droid_backends.egg-info/top_level.txt
reading manifest file 'droid_backends.egg-info/SOURCES.txt'
writing manifest file 'droid_backends.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py:788: UserWarning: The detected CUDA version (11.4) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'droid_backends' extension
Emitting ninja build file /remote-home/zengjing/GO-SLAM/build/temp.linux-x86_64-cpython-37/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: '/remote-home/zengjing/GO-SLAM/src/altcorr_kernel.cu', needed by '/remote-home/zengjing/GO-SLAM/build/temp.linux-x86_64-cpython-37/src/altcorr_kernel.o', missing and no known rule to make it
Traceback (most recent call last):
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1746, in _run_ninja_build
    env=env)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    cmdclass={ 'build_ext' : BuildExtension }
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 556, in build_extension
    depends=ext.depends,
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 571, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1424, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/root/anaconda3/envs/nice-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension`

**Comment by youmi-zym** [comment]
Hi,

I have updated the installation, please try again. thanks

Best,
Youmin

**Comment by HquGhy** [comment]
running install
/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing droid_backends.egg-info/PKG-INFO
writing dependency_links to droid_backends.egg-info/dependency_links.txt
writing top-level names to droid_backends.egg-info/top_level.txt
reading manifest file 'droid_backends.egg-info/SOURCES.txt'
writing manifest file 'droid_backends.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py:788: UserWarning: The detected CUDA version (11.7) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'droid_backends' extension
Emitting ninja build file /home/wang/GO-SLAM-main/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/local/cuda/bin/nvcc  -I/home/wang/GO-SLAM-main/thirdparty/eigen -I/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include -I/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/TH -I/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/wang/anaconda3/envs/go-slam/include/python3.7m -c -c /home/wang/GO-SLAM-main/src/lib/droid_kernels.cu -o /home/wang/GO-SLAM-main/build/temp.linux-x86_64-3.7/src/lib/droid_kernels.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=droid_backends -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/wang/GO-SLAM-main/build/temp.linux-x86_64-3.7/src/lib/droid_kernels.o 
/usr/local/cuda/bin/nvcc  -I/home/wang/GO-SLAM-main/thirdparty/eigen -I/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include -I/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/TH -I/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/wang/anaconda3/envs/go-slam/include/python3.7m -c -c /home/wang/GO-SLAM-main/src/lib/droid_kernels.cu -o /home/wang/GO-SLAM-main/build/temp.linux-x86_64-3.7/src/lib/droid_kernels.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=droid_backends -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/home/wang/GO-SLAM-main/src/lib/droid_kernels.cu:15:10: fatal error: Eigen/Sparse: No such file or directory
   15 | #include <Eigen/Sparse>
      |          ^~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1746, in _run_ninja_build
    env=env)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    cmdclass={ 'build_ext' : BuildExtension }
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 571, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1424, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/wang/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

I still have this problem after you readjusted it

**Comment by youmi-zym** [comment]
Hi,

The error is due to 

/home/wang/GO-SLAM-main/src/lib/droid_kernels.cu:15:10: fatal error: Eigen/Sparse: No such file or directory
15 | #include <Eigen/Sparse>
| ^~~~~~~~~~~~~~
compilation terminated.

Please install the Eigen correctly.

Best,
Youmin

**Comment by fokmanjyun** [comment]
If you guys find this error, you can use this order:
git clone --recursive https://github.com/youmi-zym/GO-SLAM
And then reoperate accoding to README.md.
