### ISSUE TITLE
about evaluaion of CoFusion dataset

### ISSUE THREAD

**Issue by HelloTaeyeon** [youmi-zym/GO-SLAM#37]
Hi 

Have you tried CoFusion's data set? When I verified it on your code, I reported the following error. Can you give some solutions? Thanks

#################### Results for /root/autodl-tmp/project/GO-SLAM/Datasets/CoFusion/room4 ...
Traceback (most recent call last):
  File "run.py", line 90, in <module>
    slam.terminate(rank=-1, stream=dataset)
  File "/root/autodl-tmp/project/GO-SLAM/src/slam.py", line 369, in terminate
    pose_relation=PoseRelation.translation_part, align=True, correct_scale=True)
  File "/root/miniconda3/envs/go-slam/lib/python3.7/site-packages/evo/main_ape.py", line 192, in ape
    *traj_est.align(traj_ref, correct_scale, only_scale, n=n_to_align))
  File "/root/miniconda3/envs/go-slam/lib/python3.7/site-packages/evo/core/trajectory.py", line 205, in align
    with_scale)
  File "/root/miniconda3/envs/go-slam/lib/python3.7/site-packages/evo/core/geometry.py", line 70, in umeyama_alignment
    raise GeometryException("Degenerate covariance rank, "
evo.core.geometry.GeometryException: Degenerate covariance rank, Umeyama alignment is not possible

**Comment by ArchHazel** [comment]
same issue occurred on scannet 0000_00.
